sudo: false
branches:
  only:
    - master
language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
before_install:
  - gem update --system
  - gem install bundler
script:
  - |
    for i in `seq 0 9`
    do
      BUNDLE_GEMFILE=gemfiles/rspec_3_$i.gemfile bundle install
      BUNDLE_GEMFILE=gemfiles/rspec_3_$i.gemfile bundle exec rspec spec
    done
