dist: trusty
os: linux
branches:
  only:
    - master
language: ruby
cache: bundler
env:
  global:
    - CI_NODE_TOTAL=12
matrix:
  fast_finish: true
  include:
    - rvm: 2.3.0
      env: CI_NODE_INDEX=1
    - rvm: 2.3.8
      env: CI_NODE_INDEX=2
    - rvm: 2.4.0
      env: CI_NODE_INDEX=3
    - rvm: 2.4.10
      env: CI_NODE_INDEX=4
    - rvm: 2.5.0
      env: CI_NODE_INDEX=5
    - rvm: 2.5.4
      env: CI_NODE_INDEX=6
    - rvm: 2.5.8
      env: CI_NODE_INDEX=7
    - rvm: 2.6.0
      env: CI_NODE_INDEX=8
    - rvm: 2.6.4
      env: CI_NODE_INDEX=9
    - rvm: 2.6.6
      env: CI_NODE_INDEX=10
    - rvm: 2.7.0
      env: CI_NODE_INDEX=11
    - rvm: 2.7.1
      env: CI_NODE_INDEX=12
before_install:
  - gem update --system
  - gem install bundler
  - pip install --user awscli
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
before_script:
  - ./cc-test-reporter before-build
script:
  - bundle exec rake
  - |
    for i in `seq 0 9`
    do
      BUNDLE_GEMFILE=gemfiles/rspec_3_$i.gemfile bundle install
      BUNDLE_GEMFILE=gemfiles/rspec_3_$i.gemfile bundle exec rspec spec
    done
after_script:
  - |
    if [[ "$TRAVIS_TEST_RESULT" == 0 ]]
    then
      ./cc-test-reporter format-coverage --input-type simplecov --output /var/tmp/coverage/codeclimate.$CI_NODE_INDEX.json ./coverage/.resultset.json
    fi
  - |
    if [[ "$TRAVIS_TEST_RESULT" == 0 ]]
    then
      aws s3 sync /var/tmp/coverage/ "s3://avmnu-sng/rspec-tap-formatters/$TRAVIS_BUILD_NUMBER"
    fi
  - |
    if [[ "$TRAVIS_TEST_RESULT" == 0 ]]
    then
      aws s3 sync "s3://avmnu-sng/rspec-tap-formatters/$TRAVIS_BUILD_NUMBER" /var/tmp/coverage/
    fi
  - |
    if [[ "$TRAVIS_TEST_RESULT" == 0 ]]
    then
      ./cc-test-reporter sum-coverage --output - --parts $CI_NODE_TOTAL /var/tmp/coverage/codeclimate.*.json | ./cc-test-reporter upload-coverage --input -
    fi
