sudo: false
branches:
  only:
    - master
language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - ruby-head
gemfile:
  - gemfiles/rspec-3.0-psych-2.0.gemfile
  - gemfiles/rspec-3.0-psych-2.1.gemfile
  - gemfiles/rspec-3.0-psych-2.2.gemfile
  - gemfiles/rspec-3.0-psych-3.0.gemfile
  - gemfiles/rspec-3.0-psych-3.1.gemfile
  - gemfiles/rspec-3.1-psych-2.0.gemfile
  - gemfiles/rspec-3.1-psych-2.1.gemfile
  - gemfiles/rspec-3.1-psych-2.2.gemfile
  - gemfiles/rspec-3.1-psych-3.0.gemfile
  - gemfiles/rspec-3.1-psych-3.1.gemfile
  - gemfiles/rspec-3.2-psych-2.0.gemfile
  - gemfiles/rspec-3.2-psych-2.1.gemfile
  - gemfiles/rspec-3.2-psych-2.2.gemfile
  - gemfiles/rspec-3.2-psych-3.0.gemfile
  - gemfiles/rspec-3.2-psych-3.1.gemfile
  - gemfiles/rspec-3.3-psych-2.0.gemfile
  - gemfiles/rspec-3.3-psych-2.1.gemfile
  - gemfiles/rspec-3.3-psych-2.2.gemfile
  - gemfiles/rspec-3.3-psych-3.0.gemfile
  - gemfiles/rspec-3.3-psych-3.1.gemfile
  - gemfiles/rspec-3.4-psych-2.0.gemfile
  - gemfiles/rspec-3.4-psych-2.1.gemfile
  - gemfiles/rspec-3.4-psych-2.2.gemfile
  - gemfiles/rspec-3.4-psych-3.0.gemfile
  - gemfiles/rspec-3.4-psych-3.1.gemfile
  - gemfiles/rspec-3.5-psych-2.0.gemfile
  - gemfiles/rspec-3.5-psych-2.1.gemfile
  - gemfiles/rspec-3.5-psych-2.2.gemfile
  - gemfiles/rspec-3.5-psych-3.0.gemfile
  - gemfiles/rspec-3.5-psych-3.1.gemfile
  - gemfiles/rspec-3.6-psych-2.0.gemfile
  - gemfiles/rspec-3.6-psych-2.1.gemfile
  - gemfiles/rspec-3.6-psych-2.2.gemfile
  - gemfiles/rspec-3.6-psych-3.0.gemfile
  - gemfiles/rspec-3.6-psych-3.1.gemfile
  - gemfiles/rspec-3.7-psych-2.0.gemfile
  - gemfiles/rspec-3.7-psych-2.1.gemfile
  - gemfiles/rspec-3.7-psych-2.2.gemfile
  - gemfiles/rspec-3.7-psych-3.0.gemfile
  - gemfiles/rspec-3.7-psych-3.1.gemfile
  - gemfiles/rspec-3.8-psych-2.0.gemfile
  - gemfiles/rspec-3.8-psych-2.1.gemfile
  - gemfiles/rspec-3.8-psych-2.2.gemfile
  - gemfiles/rspec-3.8-psych-3.0.gemfile
  - gemfiles/rspec-3.8-psych-3.1.gemfile
  - gemfiles/rspec-3.9-psych-2.0.gemfile
  - gemfiles/rspec-3.9-psych-2.1.gemfile
  - gemfiles/rspec-3.9-psych-2.2.gemfile
  - gemfiles/rspec-3.9-psych-3.0.gemfile
  - gemfiles/rspec-3.9-psych-3.1.gemfile
before_install:
  - gem update --system
  - gem install bundler
matrix:
  fast_finish: true
